/* Generated by scripts/gen_types.sh from schema/Brief.json. Do not edit. */

export interface Brief {
  cited_fields: string[];
  dominion_position: string;
  georgia_position: string;
  mediator_summary: string;
  shareable: string[];
  source: "llm" | "template";
}
