/* Generated by scripts/gen_types.sh from schema/Check.json. Do not edit. */

export interface Check {
  message: string;
  provenance: Provenance;
  rule_id: string;
  severity: "error" | "warn" | "info";
  subject: string;
}
export interface Provenance {
  file: string;
  locator: string;
  page: number | null;
  stage: string;
}
