/* Generated by scripts/gen_types.sh from schema/CostEstimate.json. Do not edit. */

export interface CostEstimate {
  assumptions: CostAssumption[];
  currency: string;
  high: number;
  low: number;
}
export interface CostAssumption {
  name: string;
  source: string;
  url: string | null;
  value: number | string;
}
