/* Generated by scripts/gen_types.sh from schema/CostAssumption.json. Do not edit. */

export interface CostAssumption {
  name: string;
  source: string;
  url: string | null;
  value: number | string;
}
