/* Generated by scripts/gen_types.sh from schema/Endpoint.json. Do not edit. */

export interface Endpoint {
  location: Location | null;
  name: string;
  raw_name: string;
  unlocated_reason: string | null;
}
export interface Location {
  confidence: "verified" | "high" | "town" | "low";
  evidence: string;
  lat: number;
  lon: number;
  method: "sponsor" | "overpass" | "nominatim" | "town" | "agent";
}
