/* Generated by scripts/gen_types.sh from schema/Event.json. Do not edit. */

export type Event =
  | RunStarted
  | StageStarted
  | StageCompleted
  | RecordExtracted
  | EndpointLocated
  | CheckRaised
  | OverlapFound
  | ReferenceTested
  | BriefWritten
  | RunCompleted;

export interface RunStarted {
  fixture: boolean;
  payload: RunStartedPayload;
  run_id: string;
  seq: number;
  ts: string;
  type: "run.started";
}
export interface RunStartedPayload {
  config_hash: string;
  input_hashes: {
    [k: string]: string;
  };
  today: string;
}
export interface StageStarted {
  fixture: boolean;
  payload: StageStartedPayload;
  run_id: string;
  seq: number;
  ts: string;
  type: "stage.started";
}
export interface StageStartedPayload {
  stage_id: string;
}
export interface StageCompleted {
  fixture: boolean;
  payload: StageCompletedPayload;
  run_id: string;
  seq: number;
  ts: string;
  type: "stage.completed";
}
export interface StageCompletedPayload {
  counts: {
    [k: string]: number;
  };
  duration_ms: number;
  stage_id: string;
  used_fallback: string | null;
}
export interface RecordExtracted {
  fixture: boolean;
  payload: Project;
  run_id: string;
  seq: number;
  ts: string;
  type: "record.extracted";
}
export interface Project {
  build_start: string | null;
  center: [number, number] | null;
  confidence: ("verified" | "high" | "town" | "low") | null;
  cost_by_year: {
    [k: string]: number;
  } | null;
  cost_total: number | null;
  description: string;
  endpoints: Endpoint[];
  id: string;
  in_service: string;
  length_mi: number | null;
  name: string;
  partial_location: boolean;
  provenance: Provenance;
  sponsor: string;
  status: string | null;
  utility: string;
}
export interface Endpoint {
  location: Location | null;
  name: string;
  raw_name: string;
  unlocated_reason: string | null;
}
export interface Location {
  confidence: "verified" | "high" | "town" | "low";
  evidence: string;
  lat: number;
  lon: number;
  method: "sponsor" | "overpass" | "nominatim" | "town" | "agent";
}
export interface Provenance {
  file: string;
  locator: string;
  page: number | null;
  stage: string;
}
export interface EndpointLocated {
  fixture: boolean;
  payload: EndpointLocatedPayload;
  run_id: string;
  seq: number;
  ts: string;
  type: "endpoint.located";
}
export interface EndpointLocatedPayload {
  endpoint: Endpoint;
  project_id: string;
}
export interface CheckRaised {
  fixture: boolean;
  payload: Check;
  run_id: string;
  seq: number;
  ts: string;
  type: "check.raised";
}
export interface Check {
  message: string;
  provenance: Provenance;
  rule_id: string;
  severity: "error" | "warn" | "info";
  subject: string;
}
export interface OverlapFound {
  fixture: boolean;
  payload: Overlap;
  run_id: string;
  seq: number;
  ts: string;
  type: "overlap.found";
}
export interface Overlap {
  a: string;
  b: string;
  closest_mi: number | null;
  confidence: "verified" | "high" | "town" | "low";
  distance_mi: number;
  gap_days: number;
  id: string;
  in_reference: boolean;
  windows_overlap: boolean;
}
export interface ReferenceTested {
  fixture: boolean;
  payload: ReferenceResult;
  run_id: string;
  seq: number;
  ts: string;
  type: "reference.tested";
}
export interface ReferenceResult {
  actual_days: number | null;
  actual_mi: number | null;
  expected_days: number;
  expected_mi: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  pair: [string, string];
  passed: boolean;
}
export interface BriefWritten {
  fixture: boolean;
  payload: BriefWrittenPayload;
  run_id: string;
  seq: number;
  ts: string;
  type: "brief.written";
}
export interface BriefWrittenPayload {
  brief: Brief;
  overlap_id: string;
}
export interface Brief {
  cited_fields: string[];
  dominion_position: string;
  georgia_position: string;
  mediator_summary: string;
  shareable: string[];
  source: "llm" | "template";
}
export interface RunCompleted {
  fixture: boolean;
  payload: RunCompletedPayload;
  run_id: string;
  seq: number;
  ts: string;
  type: "run.completed";
}
export interface RunCompletedPayload {
  output_hashes: {
    [k: string]: string;
  };
  status: "completed" | "failed";
  totals: {
    [k: string]: number;
  };
}
