/* Generated by scripts/gen_types.sh from schema/Location.json. Do not edit. */

export interface Location {
  confidence: "verified" | "high" | "town" | "low";
  evidence: string;
  lat: number;
  lon: number;
  method: "sponsor" | "overpass" | "nominatim" | "town" | "agent";
}
