/* Generated by scripts/gen_types.sh from schema/Opportunity.json. Do not edit. */

export interface Opportunity {
  brief: Brief | null;
  cost_estimate: CostEstimate | null;
  overlap: Overlap;
  rank: number;
  windows_overlap: boolean;
}
export interface Brief {
  cited_fields: string[];
  dominion_position: string;
  georgia_position: string;
  mediator_summary: string;
  shareable: string[];
  source: "llm" | "template";
}
export interface CostEstimate {
  assumptions: CostAssumption[];
  currency: string;
  high: number;
  low: number;
}
export interface CostAssumption {
  name: string;
  source: string;
  url: string | null;
  value: number | string;
}
export interface Overlap {
  a: string;
  b: string;
  closest_mi: number | null;
  confidence: "verified" | "high" | "town" | "low";
  distance_mi: number;
  gap_days: number;
  id: string;
  in_reference: boolean;
  windows_overlap: boolean;
}
