/* Generated by scripts/gen_types.sh from schema/Overlap.json. Do not edit. */

export interface Overlap {
  a: string;
  b: string;
  closest_mi: number | null;
  confidence: "verified" | "high" | "town" | "low";
  distance_mi: number;
  gap_days: number;
  id: string;
  in_reference: boolean;
  windows_overlap: boolean;
}
