/* Generated by scripts/gen_types.sh from schema/ReferenceResult.json. Do not edit. */

export interface ReferenceResult {
  actual_days: number | null;
  actual_mi: number | null;
  expected_days: number;
  expected_mi: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  pair: [string, string];
  passed: boolean;
}
