/* Generated by scripts/gen_types.sh from schema/ReferenceSet.json. Do not edit. */

export interface ReferenceSet {
  overlaps: Overlap[];
  projects: Project[];
  verified_coords: {
    /**
     * @minItems 2
     * @maxItems 2
     */
    [k: string]: [number, number];
  };
}
export interface Overlap {
  a: string;
  b: string;
  closest_mi: number | null;
  confidence: "verified" | "high" | "town" | "low";
  distance_mi: number;
  gap_days: number;
  id: string;
  in_reference: boolean;
  windows_overlap: boolean;
}
export interface Project {
  build_start: string | null;
  center: [number, number] | null;
  confidence: ("verified" | "high" | "town" | "low") | null;
  cost_by_year: {
    [k: string]: number;
  } | null;
  cost_total: number | null;
  description: string;
  endpoints: Endpoint[];
  id: string;
  in_service: string;
  length_mi: number | null;
  name: string;
  partial_location: boolean;
  provenance: Provenance;
  sponsor: string;
  status: string | null;
  utility: string;
}
export interface Endpoint {
  location: Location | null;
  name: string;
  raw_name: string;
  unlocated_reason: string | null;
}
export interface Location {
  confidence: "verified" | "high" | "town" | "low";
  evidence: string;
  lat: number;
  lon: number;
  method: "sponsor" | "overpass" | "nominatim" | "town" | "agent";
}
export interface Provenance {
  file: string;
  locator: string;
  page: number | null;
  stage: string;
}
