/* Generated by scripts/gen_types.sh from schema/RunState.json. Do not edit. */

export interface RunState {
  checks: Check[];
  opportunities: Opportunity[];
  overlaps: {
    [k: string]: Overlap;
  };
  projects: {
    [k: string]: Project;
  };
  reference_results: ReferenceResult[];
  run_id: string;
  stages: {
    [k: string]: StageState;
  };
  status: "running" | "completed" | "failed";
  totals: {
    [k: string]: number;
  };
}
export interface Check {
  message: string;
  provenance: Provenance;
  rule_id: string;
  severity: "error" | "warn" | "info";
  subject: string;
}
export interface Provenance {
  file: string;
  locator: string;
  page: number | null;
  stage: string;
}
export interface Opportunity {
  brief: Brief | null;
  cost_estimate: CostEstimate | null;
  overlap: Overlap;
  rank: number;
  windows_overlap: boolean;
}
export interface Brief {
  cited_fields: string[];
  dominion_position: string;
  georgia_position: string;
  mediator_summary: string;
  shareable: string[];
  source: "llm" | "template";
}
export interface CostEstimate {
  assumptions: CostAssumption[];
  currency: string;
  high: number;
  low: number;
}
export interface CostAssumption {
  name: string;
  source: string;
  url: string | null;
  value: number | string;
}
export interface Overlap {
  a: string;
  b: string;
  closest_mi: number | null;
  confidence: "verified" | "high" | "town" | "low";
  distance_mi: number;
  gap_days: number;
  id: string;
  in_reference: boolean;
  windows_overlap: boolean;
}
export interface Project {
  build_start: string | null;
  center: [number, number] | null;
  confidence: ("verified" | "high" | "town" | "low") | null;
  cost_by_year: {
    [k: string]: number;
  } | null;
  cost_total: number | null;
  description: string;
  endpoints: Endpoint[];
  id: string;
  in_service: string;
  length_mi: number | null;
  name: string;
  partial_location: boolean;
  provenance: Provenance;
  sponsor: string;
  status: string | null;
  utility: string;
}
export interface Endpoint {
  location: Location | null;
  name: string;
  raw_name: string;
  unlocated_reason: string | null;
}
export interface Location {
  confidence: "verified" | "high" | "town" | "low";
  evidence: string;
  lat: number;
  lon: number;
  method: "sponsor" | "overpass" | "nominatim" | "town" | "agent";
}
export interface ReferenceResult {
  actual_days: number | null;
  actual_mi: number | null;
  expected_days: number;
  expected_mi: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  pair: [string, string];
  passed: boolean;
}
export interface StageState {
  counts: {
    [k: string]: number;
  };
  status: "pending" | "running" | "completed" | "failed";
  used_fallback: string | null;
}
