/* Generated by scripts/gen_types.sh from schema/StageState.json. Do not edit. */

export interface StageState {
  counts: {
    [k: string]: number;
  };
  status: "pending" | "running" | "completed" | "failed";
  used_fallback: string | null;
}
