#!/usr/bin/env bash
# Generate TypeScript types in packages/contracts/ts/ from the JSON Schema in
# packages/contracts/schema/. Run via `make types`; never edit the output by hand.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
contracts="$root/packages/contracts"

rm -f "$contracts"/ts/*.ts
for schema in "$contracts"/schema/*.json; do
  name="$(basename "$schema" .json)"
  pnpm --dir "$contracts" exec json2ts \
    --input "$schema" \
    --output "$contracts/ts/$name.ts" \
    --cwd "$contracts/schema" \
    --no-additionalProperties \
    --bannerComment "/* Generated by scripts/gen_types.sh from schema/$name.json. Do not edit. */"
done
echo "generated $(ls "$contracts"/ts/*.ts | wc -l | tr -d ' ') TypeScript files in $contracts/ts"
